VIH-8971 SDS Migration Files
hmcts/vh-user-api pull request #137
Opened 2022-07-04 14:12 UTC by chris-pateman

### JIRA link (if applicable) ###
VIH-8971

### Change description ###
Add all pipeline and configuration for SDS migration

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-07-04 16:01 UTC, v1ferrarij requested changes

2022-07-04 16:01 UTC, v1ferrarij commented on variables/staging.yaml
> +    value: "staging-$(Build.SourceVersion)"
this is wrong, it should be $(Build.BuildNumber)

2022-07-04 16:01 UTC, v1ferrarij commented on variables/shared.yaml
> +    value: vhbookings
Is this right?

Do multiple API's share the vhbookings db ?

2022-07-04 16:01 UTC, v1ferrarij commented on charts/vh-user-api/values.dev.template.yaml
> +  environment:
is this not missing the SERVICES__USERAPIRESOURCEID ?

2022-07-04 16:01 UTC, v1ferrarij commented on charts/vh-user-api/values.demo.template.yaml
> +  environment:
is this not missing the SERVICES__USERAPIRESOURCEID ?

2022-07-04 16:01 UTC, v1ferrarij commented on azure-pipelines.sds.release.yml
> +# Approval Gate for Booking API Release. ############
Minor Issue - Comment still refer to Bookings

2022-07-07 07:05 UTC, v1ferrarij approved these changes
LG

2022-07-07 08:46 UTC, agovind92 approved these changes

2022-07-07 08:46 UTC, merged